# Generated by Django 4.0.4 on 2022-06-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('Suggest a Feature', 'Suggest a Feature'), ('Noticed a Bug', 'Noticed a Bug'), ('Need Support', 'Need Support')], max_length=20)),
                ('video_url', models.CharField(max_length=300)),
                ('screenshot_url', models.CharField(max_length=300)),
                ('issue_page_url', models.CharField(max_length=200)),
                ('feedback_content', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackSender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='UserNotificationSettings',
        ),
    ]
