# Generated by Django 4.0.4 on 2022-06-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedback_remove_usernotificationsettings_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='issue_page_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='screenshot_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='video_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
