# Generated by Django 4.0.4 on 2022-06-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_feedback_issue_page_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
