# Generated by Django 4.0.4 on 2022-06-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_feedback_feedback_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
