# Generated by Django 4.0.4 on 2022-06-01 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('contact_user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactUserAccount', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycontact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=2000)),
                ('meeting_time_realization', models.IntegerField(help_text='How many minutes did the meeting take?')),
                ('meeting_priority', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('has_comments', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('contacts', models.ManyToManyField(related_name='teamContacts', to='note.contact')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myteam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectteam', to='note.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myproject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('meeting_time_goal', models.IntegerField(help_text='How many minutes should the meeting last?')),
                ('sometimes_record', models.BooleanField(default=False)),
                ('meeting_room_link', models.CharField(max_length=2000)),
                ('scheduled_time', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mymeetingformsettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meeting Forms',
            },
        ),
        migrations.CreateModel(
            name='MeetingFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('form_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.meetingformsettings')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mymeetingformquestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFormEntryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=5000)),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotationAuthor', to=settings.AUTH_USER_MODEL)),
                ('form_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.meetingformentry')),
            ],
        ),
        migrations.AddField(
            model_name='meetingformentry',
            name='form_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.meetingformsettings'),
        ),
        migrations.AddField(
            model_name='meetingformentry',
            name='notify_user_list',
            field=models.ManyToManyField(related_name='meetingNotify', to='note.contact'),
        ),
        migrations.AddField(
            model_name='meetingformentry',
            name='participants',
            field=models.ManyToManyField(related_name='meetingParticipants', to='note.contact'),
        ),
        migrations.AddField(
            model_name='meetingformentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mymeetingformentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeetingFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_response', models.CharField(max_length=1200)),
                ('input_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.meetingformquestion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mymeetingformanswer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.meetingformentrycomment')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.contact')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.meetingformentry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertIsFor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
