# Generated by Django 4.0.4 on 2022-06-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_meetingformentry_viewed_by_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingformentry',
            name='has_comments',
        ),
    ]
